### ISSUE TITLE
gst_object_set_properties_from_uri_query_parameters

### ISSUE THREAD

**Issue by woutervanh** [mleeman/gst-plugins-rtp#1]
When I build this code, I get undefined reference to 'gst_object_set_properties_from_uri_query_parameters' errors. I don't understand this, as on the frontpage it's stated that it's no longer dependent of those?
Now I have to say I was able to build it earlier, before you moved to meson (which I'm not familiar with). Something has changed?

**Comment by mleeman** [comment]
gst_object_set_properties_from_uri_query_parameters does what it describes: it takes the key/value pairs from the query part of a URI and sets it on the object. Some upstream elements do this already, but there is no consistent way of doing it.

We've added a patch to core but it was not yet integrated.

The code itself is included in src/ but it seems that the meson build does not yet detect if GStreamer core was patched or not to add the files. A simple workaround would be to add the gst_object_set_properties_from_uri_query_parameters.c file into the list of to be compiled sources in src/meson.build

I'll have a look to enable the detection again for patched/unpatched core.

**Comment by woutervanh** [comment]
Yes, that's what I did now, added the c file to the src/meson.build and remove the -DHAVE_URI_....... from meson.build global C-flags. Now it compiles.

**Comment by mleeman** [comment]
fix is pending

**Comment by woutervanh** [comment]
Great!
