### ISSUE TITLE
Un-namespaced element factory names

### ISSUE THREAD

**Issue by sdroege** [mleeman/gst-plugins-rtp#1]
Currently the elements in this plugin use `rtpsink` and `rtpsrc` as element factory names, i.e. without any additional namespace prefix. This is reserved for elements provided by the GStreamer project.

Such elements might be added there sooner or later, which would then create a conflict with these.

**Comment by mleeman** [comment]
I did want to get the elements in for years, but the last attempt got stuck on the discussion on the naming of and the use/side effects of the uri parsing.

Renaming the elements to nrtp_rtpsink and nrtp_rtpsrc would be enough? I am bad in naming (and inventing them).

**Comment by mleeman** [comment]
part of plugins bad now
